---
name: InfiniTime
version: 0.0.24

slug: infinitime
description: BLE addon that interfaces with watches running infinitime
startup: application
boot: auto
init: false
homeassistant_api: True
auth_api: True
map:
  - config:rw
  - ssl
url: https://github.com/cpyarger/Home-Assistant-Addons/tree/master/InfiniTime
usb: true
host_network: False
host_dbus: True
arch:
  - aarch64
  - amd64
  - armv7
  - i386
